services:
  ticket-annd:
    image: ticket-annd
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:8081"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - ticket-net
    depends_on:
      - mongo
      - mongo-express
      - redis
    
  mongo:
    image: 'mongo:7.0.5'
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/var/lib/mongodb/data
    networks:
      - ticket-net
  mongo-express:
    image: 'mongo-express:1.0.2'
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password
    networks:
      - ticket-net
  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    networks:
      - ticket-net
volumes:
  mongo-data:
    
networks:
  ticket-net:
    driver: bridge

